In [4]:
import numpy as np
a = np.random.random((3,3,3))
print(a)


[[[0.11393165 0.84004647 0.50122353]
  [0.91489098 0.57998273 0.24833098]
  [0.01855973 0.1645956  0.81321127]]

 [[0.45904489 0.29179541 0.38592411]
  [0.76392125 0.82435784 0.03020598]
  [0.42739262 0.99196627 0.15748816]]

 [[0.71540582 0.09238877 0.24077313]
  [0.69003384 0.58316112 0.02814089]
  [0.47056893 0.41548136 0.51771435]]]


In [11]:
b = np.diag(1+np.arange(4), k = -1)
print(b)

[[0 0 0 0 0]
 [1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]]


In [15]:
c = np.zeros ((8,8), dtype=int)
c[1::2, ::2]= 2
c[::2, 1::2] = 1
print (c)

[[0 1 0 1 0 1 0 1]
 [2 0 2 0 2 0 2 0]
 [0 1 0 1 0 1 0 1]
 [2 0 2 0 2 0 2 0]
 [0 1 0 1 0 1 0 1]
 [2 0 2 0 2 0 2 0]
 [0 1 0 1 0 1 0 1]
 [2 0 2 0 2 0 2 0]]


In [17]:
Z=np.random.random((5,5))
Zmax, Zmin = Z.max(), Z.min()
Z= (Z-Zmin)/(Zmax-Zmin)
print (Z)

[[0.82279276 0.14797671 0.87132067 0.57876892 0.85053443]
 [0.77062568 0.68145178 0.15610746 0.47847798 0.65456228]
 [0.31138246 0.31380289 0.46067327 0.52592555 0.24442076]
 [0.93127821 0.36232245 0.76156151 0.83770723 0.21455838]
 [1.         0.38849082 0.         0.28868089 0.30432032]]


In [18]:
import numpy as np
array1 = np.array([10, 20, 40, 60,80,45])
print("Array1: ",array1)
array2 = [10, 30, 40,80,90,50,45]
print("Array2: ",array2)
print("Common values between two arrays:")
print(np.intersect1d(array1, array2))

Array1:  [10 20 40 60 80 45]
Array2:  [10, 30, 40, 80, 90, 50, 45]
Common values between two arrays:
[10 40 45 80]


In [19]:
import numpy as np
yesterday = np.datetime64('today', 'D') - np.timedelta64(1, 'D')
print("Yestraday: ",yesterday)
today     = np.datetime64('today', 'D')
print("Today: ",today)
tomorrow  = np.datetime64('today', 'D') + np.timedelta64(1, 'D')
print("Tomorrow: ",tomorrow)

Yestraday:  2020-07-27
Today:  2020-07-28
Tomorrow:  2020-07-29


In [20]:
A1 = np.random.randint(0,2,10)
A2 = np.random.randint(0,2,10)
equal = np.allclose(A1,A2)
print(A1)
print(A2)
print(equal)


[0 0 0 1 0 0 0 1 1 1]
[0 1 0 0 1 1 0 0 0 0]
False


In [21]:
vector = np.random.random(10)
print("The Random Vector :\n", vector)
vector[vector.argmax()] = 0
print("The Replace vector :\n",vector)

The Random Vector :
 [0.81551998 0.75962186 0.48989525 0.69388756 0.48957567 0.42513103
 0.82901959 0.58898231 0.89388704 0.02720619]
The Replace vector :
 [0.81551998 0.75962186 0.48989525 0.69388756 0.48957567 0.42513103
 0.82901959 0.58898231 0.         0.02720619]


In [23]:
import numpy as np 

with np.printoptions(precision = 3): 
     print(np.zeros((10,10)))

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]


In [24]:
X = np.random.rand(3,3)

Y = X - X.mean(axis=1).reshape(-1, 1)

Y

array([[ 0.26022748,  0.27246091, -0.53268839],
       [ 0.10003519, -0.0093001 , -0.09073509],
       [ 0.27308073, -0.08515126, -0.18792947]])

In [25]:
Z = np.ones(5)
print(Z)
I = np.random.randint(0,len(Z),10)
print(I)
Z += np.bincount(I, minlength=len(Z))
print(Z)


[1. 1. 1. 1. 1.]
[4 4 0 1 0 4 2 2 1 1]
[3. 4. 3. 1. 4.]


In [26]:
A = np.random.randint(0,10,(3,3))
B= np.random.randint(0,10,(3,3))
#Slow version
print(A)
print(B)

np.diag(np.dot(A, B))
np.sum(A * B.T, axis=1)
np.einsum("ij,ji->i", A, B)

[[1 9 3]
 [7 1 3]
 [5 1 4]]
[[1 6 3]
 [2 1 9]
 [7 1 2]]


array([40, 46, 32])

In [27]:
arr = np.random.randint(0,10,20)
print (arr)
print('rank:', np.bincount(arr).argmax())

[9 6 0 3 1 9 9 7 0 7 1 7 0 5 4 3 3 7 2 1]
rank: 7


In [28]:
Z = np.arange(100)
np.random.shuffle(Z)
n = 5

print (Z[np.argsort(Z)[-n:]])

[95 96 97 98 99]


In [33]:
a = np.array([("Lets", 1, 3),
              ("Upgrade", 3, 2)])
b = np.core.records.fromarrays(a.T,
                               names='col1, col2, col3',
                               formats = 'S8, f8, i8')
print(a)
print(b)


[['Lets' '1' '3']
 ['Upgrade' '3' '2']]
[(b'Lets', 1., 3) (b'Upgrade', 3., 2)]
